---
AWSTemplateFormatVersion: '2010-09-09'
Resources:
  MySecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow SSH and HTTP access
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          CidrIp: 0.0.0.0/0

  MyEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      ImageId: ami-0b5eea76982371e91
      KeyName: A4LKeyPair
      SecurityGroups:
        - !Ref MySecurityGroup
      UserData: 
        Fn::Base64: !Sub |
          #!/bin/bash
          
          sudo yum update -y

          sudo yum install git -y

          sudo yum install zlib-devel bzip2 bzip2-devel readline-devel sqlite sqlite-devel openssl-devel xz xz-devel libffi-devel gcc
          
          curl -L https://github.com/pyenv/pyenv-installer/raw/master/bin/pyenv-installer | bash
          
          mv /.pyenv /home/ec2-user/
          
          chown ec2-user:ec2-user -R /home/ec2-user/.pyenv

          echo "export PYENV_ROOT="\$HOME/.pyenv"" >>/home/ec2-user/.bashrc

          echo "command -v pyenv >/dev/null || export PATH="\$PYENV_ROOT/bin:\$PATH"" >>/home/ec2-user/.bashrc

          echo "eval \"\$(pyenv init -)\"" >>/home/ec2-user/.bashrc

          echo "eval \"\$(pyenv virtualenv-init -)\"" >>/home/ec2-user/.bashrc
          
          sudo yum group install "Development Tools"

          pyenv install 3.9.13

          pyenv virtualenv 3.9.13 totogi

          pyenv global totogi

          git clone https://github.com/totogi/test_data_generator.git
          
          mv /test_data_generator /home/ec2-user/

          chown ec2-user:ec2-user -R /home/ec2-user/test_data_generator
          
          mkdir /home/ec2-user/test_data_generator/logs /home/ec2-user/test_data_generator/dbfile
          
          chown ec2-user:ec2-user -R /home/ec2-user/test_data_generator/logs
          
          chown ec2-user:ec2-user -R /home/ec2-user/test_data_generator/dbfile
          
          pip3 install -r test_data_generator/requirements.txt
